server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.eying.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrix #自定义带熔断器的服务名称信息
    prefer-ip-address: true
info:
  app.name: ${spring.application.name}
  company.name: www.eying.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@


